import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';

type SortBy = 'default' | 'az' | 'za';

interface Product {
  id: number;
  name: string;
  price: number;
  weight: string;
  category: string;
  description: string;
  image: string;
  stock: boolean;
}

@Component({
  selector: 'app-products',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './products.html',
  styleUrl: './products.css',
})
export class Products {
  selectedCategory = 'Todos';
  sortBy: SortBy = 'default';

  get categories(): string[] {
    return ['Todos', ...new Set(this.products.map(product => product.category))];
  }

  products: Product[] = [
    {
      id: 1,
      name: 'Tallarines Yemita',
      price: 0,
      weight: '500g',
      category: 'Pasta Larga',
      description: 'Tallarines frescos de yemita, ideales para acompañar con tuco, boloñesa o salsa casera.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 2,
      name: 'Tallarines de Espinaca',
      price: 0,
      weight: '500g',
      category: 'Pasta Larga',
      description: 'Tallarines frescos con espinaca, de sabor suave y textura artesanal.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 3,
      name: 'Tallarines de Morrón',
      price: 0,
      weight: '500g',
      category: 'Pasta Larga',
      description: 'Tallarines frescos con morrón, una opción sabrosa y diferente para todos los días.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 4,
      name: 'Tallarines Caseros Don Raúl',
      price: 0,
      weight: '500g',
      category: 'Pasta Larga',
      description: 'Tallarines caseros tradicionales, elaborados con receta artesanal.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 5,
      name: 'Fussiles',
      price: 0,
      weight: '500g',
      category: 'Pasta Corta',
      description: 'Pasta corta fresca, ideal para salsas cremosas o con mucho sabor.',
      image: 'assets/images/products/5.jpg',
      stock: true,
    },
    {
      id: 6,
      name: 'Mostacholes',
      price: 0,
      weight: '500g',
      category: 'Pasta Corta',
      description: 'Mostacholes frescos artesanales, perfectos para acompañar con salsa roja o blanca.',
      image: 'assets/images/products/6.jpg',
      stock: true,
    },
    {
      id: 7,
      name: 'Tallarines Tinta de Calamar',
      price: 0,
      weight: '500g',
      category: 'Pasta Larga',
      description: 'Tallarines especiales con tinta de calamar, de sabor intenso y presentación diferente.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 8,
      name: 'Ravioles de Ricota, Jamón y Queso',
      price: 0,
      weight: '1 caja',
      category: 'Pasta Rellena',
      description: 'Ravioles frescos rellenos de ricota, jamón y queso. Un clásico artesanal.',
      image: 'assets/images/products/8.jpg',
      stock: true,
    },
    {
      id: 9,
      name: 'Ravioles de Ricota y Verdura',
      price: 0,
      weight: '1 caja',
      category: 'Pasta Rellena',
      description: 'Ravioles frescos rellenos de ricota y verdura, suaves y sabrosos.',
      image: 'assets/images/products/9.jpg',
      stock: true,
    },
    {
      id: 10,
      name: 'Ravioles de Ricota y Queso',
      price: 0,
      weight: '1 caja',
      category: 'Pasta Rellena',
      description: 'Ravioles artesanales con relleno cremoso de ricota y queso.',
      image: 'assets/images/products/10.jpg',
      stock: true,
    },
    {
      id: 11,
      name: 'Ravioles de Pollo, Jamón y Verdura',
      price: 0,
      weight: '1 caja',
      category: 'Pasta Rellena',
      description: 'Ravioles frescos con relleno de pollo, jamón y verdura.',
      image: 'assets/images/products/11.jpg',
      stock: true,
    },
    {
      id: 12,
      name: 'Ravioles de Pollo, Carne y Verdura',
      price: 0,
      weight: '1 caja',
      category: 'Pasta Rellena',
      description: 'Ravioles artesanales con relleno abundante de pollo, carne y verdura.',
      image: 'assets/images/products/12.jpg',
      stock: true,
    },
    {
      id: 13,
      name: 'Ravioles de Seso y Verdura',
      price: 0,
      weight: '1 caja',
      category: 'Pasta Rellena',
      description: 'Ravioles tradicionales rellenos con seso y verdura.',
      image: 'assets/images/products/13.jpg',
      stock: true,
    },
    {
      id: 14,
      name: 'Raviolones de Ricota, Jamón y Nuez',
      price: 0,
      weight: '1 caja',
      category: 'Pasta Rellena',
      description: 'Raviolones grandes con relleno de ricota, jamón y nuez.',
      image: 'assets/images/products/14.jpg',
      stock: true,
    },
    {
      id: 15,
      name: 'Raviolones de Pollo, Jamón y Verdura',
      price: 0,
      weight: '1 caja',
      category: 'Pasta Rellena',
      description: 'Raviolones artesanales rellenos de pollo, jamón y verdura.',
      image: 'assets/images/products/15.jpg',
      stock: true,
    },
    {
      id: 16,
      name: 'Raviolones de Calabaza',
      price: 0,
      weight: '1 caja',
      category: 'Pasta Rellena',
      description: 'Raviolones frescos con relleno suave de calabaza.',
      image: 'assets/images/products/16.jpg',
      stock: true,
    },
    {
      id: 17,
      name: 'Raviolones a los Cuatro Quesos',
      price: 0,
      weight: '1 caja',
      category: 'Pasta Rellena',
      description: 'Raviolones rellenos con una mezcla cremosa de cuatro quesos.',
      image: 'assets/images/products/17.jpg',
      stock: true,
    },
    {
      id: 18,
      name: 'Raviolones de Vacío y Provoleta',
      price: 0,
      weight: '1 caja',
      category: 'Pasta Rellena',
      description: 'Raviolones especiales rellenos de vacío y provoleta.',
      image: 'assets/images/products/18.jpg',
      stock: true,
    },
    {
      id: 19,
      name: 'Raviolones de Osobuco',
      price: 0,
      weight: '1 caja',
      category: 'Pasta Rellena',
      description: 'Raviolones especiales con relleno de osobuco, intensos y sabrosos.',
      image: 'assets/images/products/19.jpg',
      stock: true,
    },
    {
      id: 20,
      name: 'Raviolones de Bondiola',
      price: 0,
      weight: '1 caja',
      category: 'Pasta Rellena',
      description: 'Raviolones artesanales rellenos de bondiola.',
      image: 'assets/images/products/20.jpg',
      stock: true,
    },
    {
      id: 21,
      name: 'Tortelitis de Pollo, Jamón y Queso',
      price: 0,
      weight: '250g',
      category: 'Pasta Rellena',
      description: 'Tortelitis frescos rellenos de pollo, jamón y queso.',
      image: 'assets/images/products/21.jpg',
      stock: true,
    },
    {
      id: 22,
      name: 'Sorrentinos de Muzzarella y Jamón',
      price: 0,
      weight: '1 plancha',
      category: 'Pasta Rellena',
      description: 'Sorrentinos grandes rellenos de muzzarella y jamón.',
      image: 'assets/images/products/22.jpg',
      stock: true,
    },
    {
      id: 23,
      name: 'Sorrentinos Caprese',
      price: 0,
      weight: '1 plancha',
      category: 'Pasta Rellena',
      description: 'Sorrentinos frescos estilo caprese, una opción suave y sabrosa.',
      image: 'assets/images/products/23.jpg',
      stock: true,
    },
    {
      id: 24,
      name: 'Lasagna de Ricota y Jamón',
      price: 0,
      weight: '1 porción',
      category: 'Para Horno',
      description: 'Lasagna artesanal rellena de ricota y jamón, lista para horno o microondas.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 25,
      name: 'Lasagna de Ricota, Jamón y Verdura',
      price: 0,
      weight: '1 porción',
      category: 'Para Horno',
      description: 'Lasagna fresca con ricota, jamón y verdura.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 26,
      name: 'Lasagna de Pollo, Jamón y Verdura',
      price: 0,
      weight: '1 porción',
      category: 'Para Horno',
      description: 'Lasagna artesanal con relleno de pollo, jamón y verdura.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 27,
      name: 'Lasagna de Carne y Huevo',
      price: 0,
      weight: '1 porción',
      category: 'Para Horno',
      description: 'Lasagna casera rellena de carne y huevo.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 28,
      name: 'Agnolotis de Ricota, Jamón y Nuez',
      price: 0,
      weight: '500g',
      category: 'Pasta Rellena',
      description: 'Agnolotis frescos rellenos de ricota, jamón y nuez.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 29,
      name: 'Agnolotis de Ricota y Jamón',
      price: 0,
      weight: '500g',
      category: 'Pasta Rellena',
      description: 'Agnolotis artesanales con relleno de ricota y jamón.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 30,
      name: 'Agnolotis de Jamón y Muzzarella',
      price: 0,
      weight: '500g',
      category: 'Pasta Rellena',
      description: 'Agnolotis frescos rellenos de jamón y muzzarella.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 31,
      name: 'Arrollados de Ricota',
      price: 0,
      weight: '4 unidades',
      category: 'Para Horno',
      description: 'Arrollados caseros de ricota, ideales para acompañar con salsa.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 32,
      name: 'Arrollados de Jamón',
      price: 0,
      weight: '4 unidades',
      category: 'Para Horno',
      description: 'Arrollados frescos de jamón, listos para calentar y servir.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 33,
      name: 'Arrollados de Pollo y Verdura',
      price: 0,
      weight: '4 unidades',
      category: 'Para Horno',
      description: 'Arrollados rellenos de pollo y verdura, con opción de salsa.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 34,
      name: 'Prepizza Casera de Tomate',
      price: 0,
      weight: '1 unidad',
      category: 'Pizzas y Tapas',
      description: 'Prepizza casera de tomate, lista para agregar ingredientes y hornear.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 35,
      name: 'Pizzetas',
      price: 0,
      weight: '12 unidades',
      category: 'Pizzas y Tapas',
      description: 'Pizzetas caseras listas para preparar.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 36,
      name: 'Tapas de Empanadas',
      price: 0,
      weight: '1 paquete',
      category: 'Pizzas y Tapas',
      description: 'Tapas frescas para empanadas, listas para rellenar.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 37,
      name: 'Tapas de Canelones',
      price: 0,
      weight: '1 paquete',
      category: 'Para Horno',
      description: 'Tapas frescas para preparar canelones caseros.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 38,
      name: 'Salsa Tuco',
      price: 0,
      weight: '250g',
      category: 'Salsas',
      description: 'Salsa casera tipo tuco, ideal para acompañar pastas frescas.',
      image: 'assets/images/products/38.jpg',
      stock: true,
    },
    {
      id: 39,
      name: 'Salsa Bolognesa',
      price: 0,
      weight: '250g',
      category: 'Salsas',
      description: 'Salsa bolognesa casera, con sabor tradicional y buena consistencia.',
      image: 'assets/images/products/39.jpg',
      stock: true,
    },
    {
      id: 40,
      name: 'Salsa Blanca',
      price: 0,
      weight: '250g',
      category: 'Salsas',
      description: 'Salsa blanca casera, cremosa y suave.',
      image: 'assets/images/products/40.jpg',
      stock: true,
    },
    {
      id: 41,
      name: 'Salsa Cuatro Quesos',
      price: 0,
      weight: '250g',
      category: 'Salsas',
      description: 'Salsa cremosa de cuatro quesos, ideal para pastas rellenas.',
      image: 'assets/images/products/41.jpg',
      stock: true,
    },
    {
      id: 42,
      name: 'Pesto Casero',
      price: 0,
      weight: '250g',
      category: 'Salsas',
      description: 'Pesto casero fresco, perfecto para pastas largas o rellenas.',
      image: 'assets/images/products/42.jpg',
      stock: true,
    },
    {
      id: 43,
      name: 'Raviolón de Calabaza y Muzzarella',
      price: 0,
      weight: '1 caja',
      category: 'Vegetarianas',
      description: 'Raviolón vegetariano relleno de calabaza y muzzarella.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 44,
      name: 'Raviolón Cuatro Quesos',
      price: 0,
      weight: '1 caja',
      category: 'Vegetarianas',
      description: 'Raviolón vegetariano relleno con mezcla de cuatro quesos.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 45,
      name: 'Ravioles con Salsa',
      price: 0,
      weight: '1 porción',
      category: 'Para Llevar',
      description: 'Ravioles listos para llevar, servidos con salsa.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 46,
      name: 'Tallarines con Salsa',
      price: 0,
      weight: '1 porción',
      category: 'Para Llevar',
      description: 'Tallarines listos para llevar, acompañados con salsa casera.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 47,
      name: 'Ñoquis con Salsa',
      price: 0,
      weight: '1 porción',
      category: 'Para Llevar',
      description: 'Ñoquis listos para llevar, servidos con salsa.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 48,
      name: 'Torteletis con Salsa',
      price: 0,
      weight: '1 porción',
      category: 'Para Llevar',
      description: 'Torteletis listos para llevar, acompañados con salsa.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 49,
      name: 'Canelones con Salsa',
      price: 0,
      weight: '3 unidades',
      category: 'Para Llevar',
      description: 'Canelones listos para llevar, servidos con salsa.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 50,
      name: 'Lasagna con Salsa',
      price: 0,
      weight: '1 porción',
      category: 'Para Llevar',
      description: 'Lasagna lista para llevar, acompañada con salsa.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 51,
      name: 'Canelones de Ricota, Jamón y Queso',
      price: 0,
      weight: '3 unidades',
      category: 'Para Horno',
      description: 'Canelones frescos rellenos de ricota, jamón y queso.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 52,
      name: 'Canelones de Pollo, Jamón y Verdura',
      price: 0,
      weight: '3 unidades',
      category: 'Para Horno',
      description: 'Canelones caseros rellenos de pollo, jamón y verdura.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 53,
      name: 'Canelones de Jamón y Muzzarella',
      price: 0,
      weight: '3 unidades',
      category: 'Para Horno',
      description: 'Canelones frescos rellenos de jamón y muzzarella.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 54,
      name: 'Canelones de Ricota, Jamón y Verdura',
      price: 0,
      weight: '3 unidades',
      category: 'Para Horno',
      description: 'Canelones artesanales con relleno de ricota, jamón y verdura.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 55,
      name: 'Canelones de Ricota, Jamón y Nuez',
      price: 0,
      weight: '3 unidades',
      category: 'Para Horno',
      description: 'Canelones frescos rellenos de ricota, jamón y nuez.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 56,
      name: 'Panqueques con Salsa',
      price: 0,
      weight: '1 porción',
      category: 'Para Horno',
      description: 'Panqueques caseros listos para calentar, servidos con salsa.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 57,
      name: 'Fideos Rellenos de Ricota y Queso',
      price: 0,
      weight: '500g',
      category: 'Pasta Rellena',
      description: 'Fideos rellenos frescos con ricota y queso.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 58,
      name: 'Fideos Rellenos de Pollo y Verdura',
      price: 0,
      weight: '500g',
      category: 'Pasta Rellena',
      description: 'Fideos rellenos artesanales de pollo y verdura.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 59,
      name: 'Ñoquis de Papa',
      price: 0,
      weight: '300g',
      category: 'Ñoquis',
      description: 'Ñoquis frescos de papa, tiernos y clásicos.',
      image: 'assets/images/products/59.jpg',
      stock: true,
    },
    {
      id: 60,
      name: 'Ñoquis de Morrón y Espinaca',
      price: 0,
      weight: '300g',
      category: 'Ñoquis',
      description: 'Ñoquis frescos combinados con morrón y espinaca.',
      image: 'assets/images/products/60.jpg',
      stock: true,
    },
    {
      id: 61,
      name: 'Ñoquis de Ricota',
      price: 0,
      weight: '300g',
      category: 'Ñoquis',
      description: 'Ñoquis suaves de ricota, livianos y artesanales.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 62,
      name: 'Ñoquis Tricolor',
      price: 0,
      weight: '300g',
      category: 'Ñoquis',
      description: 'Ñoquis tricolor frescos, ideales para una comida casera y colorida.',
      image: 'assets/images/products/62.jpg',
      stock: true,
    },
    {
      id: 63,
      name: 'Postre Massini',
      price: 0,
      weight: '1 unidad',
      category: 'Postres',
      description: 'Postre clásico Massini, ideal para acompañar después de una buena pasta.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 64,
      name: 'Postre Balcarce',
      price: 0,
      weight: '1 unidad',
      category: 'Postres',
      description: 'Postre Balcarce tradicional, dulce y cremoso.',
      image: 'assets/images/products/0.png',
      stock: true,
    },
    {
      id: 65,
      name: 'Tiramisú',
      price: 0,
      weight: '1 unidad',
      category: 'Postres',
      description: 'Tiramisú clásico, suave y cremoso.',
      image: 'assets/images/products/65.png',
      stock: true,
    },
  ];

  get filteredProducts(): Product[] {
    const filtered = this.products.filter(
      (product) =>
        this.selectedCategory === 'Todos' ||
        product.category === this.selectedCategory
    );

    return [...filtered].sort((a, b) => {
      if (this.sortBy === 'az') {
        return a.name.localeCompare(b.name, 'es');
      }

      if (this.sortBy === 'za') {
        return b.name.localeCompare(a.name, 'es');
      }

      return 0;
    });
  }

  selectCategory(category: string): void {
    this.selectedCategory = category;
  }

  // handleAddToCart(product: Product): void {
  //   if (!product.stock) return;

  //   console.log('Agregar al carrito:', product);

  //   // Acá después podés conectar tu servicio:
  //   // this.cartService.addItem(product);
  //   // this.cartService.openCart();
  // }
}